name = "ConjGrad"
uuid = "c16e2fb6-b1e3-11e9-21be-0f591a3b69ea"
authors = ["Stefano Mandeli <stefano.mandelli@unimi.it>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[compat]
julia = "1"
